import { UserProps } from "types"

export const exploreList = [
	{
		about:
			"Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "rbritney0@netvibes.com",
		id: "625d81d1-c7b0-4400-86f8-959c3dbd628f",
		imageUrl: "https://robohash.org/solutaeosmolestias.png?size=50x50&set=set1",
		location: "Stari Grad",
		name: "Randolph Britney",
		role: "Editor",
		username: "rbritney0",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "mkay1@about.com",
		id: "66fb15e3-cdbb-45f7-b2bd-9bc477633855",
		imageUrl: "https://robohash.org/nobisfacilisaliquam.png?size=50x50&set=set1",
		location: "Barreiros",
		name: "Morgan Kay",
		role: "Administrative Officer",
		username: "mkay1",
		website: "https://opensause.vercel.app",
	},
	{
		about: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "reustis2@wunderground.com",
		id: "aa97b783-1c28-4fb8-8d5a-8426c9912611",
		imageUrl: "https://robohash.org/autestcorporis.png?size=50x50&set=set1",
		location: "Banjar Yehsatang",
		name: "Richmond Eustis",
		role: "Account Coordinator",
		username: "reustis2",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "eellor3@cdc.gov",
		id: "47d90e61-3796-4a91-a5c2-bacf7324f592",
		imageUrl:
			"https://robohash.org/quisquamearumrepellendus.png?size=50x50&set=set1",
		location: "Chuangye",
		name: "Ernestus Ellor",
		role: "Senior Developer",
		username: "eellor3",
		website: "https://opensause.vercel.app",
	},
	{
		about: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "blilley4@cdbaby.com",
		id: "a7c283f5-7b56-4335-be75-76590740e8e0",
		imageUrl: "https://robohash.org/delectusteneturenim.png?size=50x50&set=set1",
		location: "Matmata",
		name: "Beverley Lilley",
		role: "Project Manager",
		username: "blilley4",
		website: "https://opensause.vercel.app",
	},
	{
		about: "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "fcranna5@icio.us",
		id: "162ca70b-7d02-4182-8813-1f79a6f59b56",
		imageUrl: "https://robohash.org/totamnamexplicabo.png?size=50x50&set=set1",
		location: "Witihama",
		name: "Felicle Cranna",
		role: "Chief Design Engineer",
		username: "fcranna5",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "eolver6@e-recht24.de",
		id: "277bfbfe-66c5-47df-9a48-87db6b571b64",
		imageUrl: "https://robohash.org/estvoluptasaut.png?size=50x50&set=set1",
		location: "Challhuahuacho",
		name: "Emera Olver",
		role: "Clinical Specialist",
		username: "eolver6",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "abreslauer7@shop-pro.jp",
		id: "b1b8ed79-ce34-4888-aa35-7a0b55bd93c3",
		imageUrl: "https://robohash.org/veritatiseteveniet.png?size=50x50&set=set1",
		location: "Kajan",
		name: "Angelico Breslauer",
		role: "GIS Technical Architect",
		username: "abreslauer7",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "pislep8@google.de",
		id: "71e654f7-db44-4194-91de-12fa7e555f6a",
		imageUrl: "https://robohash.org/inquisquia.png?size=50x50&set=set1",
		location: "Quesada",
		name: "Perkin Islep",
		role: "Chemical Engineer",
		username: "pislep8",
		website: "https://opensause.vercel.app",
	},
	{
		about: "In congue. Etiam justo. Etiam pretium iaculis justo.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "jyakubovich9@github.com",
		id: "480a6f30-a18a-47df-8a86-82e76e01bf2a",
		imageUrl: "https://robohash.org/isteatsunt.png?size=50x50&set=set1",
		location: "Taboc",
		name: "Jillie Yakubovich",
		role: "Graphic Designer",
		username: "jyakubovich9",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "sdellara@google.de",
		id: "b8ed27a5-9891-4822-9600-bc33e9e356d1",
		imageUrl: "https://robohash.org/autquaeratsed.png?size=50x50&set=set1",
		location: "Kadubincarung",
		name: "Susanne Dellar",
		role: "Design Engineer",
		username: "sdellara",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "rfazanb@wired.com",
		id: "1be406ff-f054-4ea6-9a98-e6d498d010e3",
		imageUrl: "https://robohash.org/undeodioaut.png?size=50x50&set=set1",
		location: "Baabda",
		name: "Roxine Fazan",
		role: "Clinical Specialist",
		username: "rfazanb",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "dlempennyc@wikimedia.org",
		id: "86baa2b6-9db6-410d-aa99-be8fe48da319",
		imageUrl: "https://robohash.org/omnisquiasperiores.png?size=50x50&set=set1",
		location: "Aguisan",
		name: "Dolorita Lempenny",
		role: "Engineer III",
		username: "dlempennyc",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "ffeasterd@geocities.com",
		id: "ed6411c5-0dfb-4405-b017-c9c1f136048f",
		imageUrl: "https://robohash.org/quiuterror.png?size=50x50&set=set1",
		location: "Bacong",
		name: "Flynn Feaster",
		role: "Chief Design Engineer",
		username: "ffeasterd",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "jwhatleye@chronoengine.com",
		id: "35853edd-a0cf-42c1-9fcb-e983737cd2bc",
		imageUrl: "https://robohash.org/magnamquaeratfuga.png?size=50x50&set=set1",
		location: "Onega",
		name: "Jeffrey Whatley",
		role: "Editor",
		username: "jwhatleye",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "cnellenf@earthlink.net",
		id: "eaea107d-6057-4292-b36f-69ff18b2117d",
		imageUrl: "https://robohash.org/natusquiafugit.png?size=50x50&set=set1",
		location: "Qiping",
		name: "Carita Nellen",
		role: "Quality Control Specialist",
		username: "cnellenf",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "fchaulkg@rediff.com",
		id: "30a442b0-464e-4b84-9e66-93459ad767be",
		imageUrl: "https://robohash.org/numquametvoluptates.png?size=50x50&set=set1",
		location: "Tomsk",
		name: "Fabio Chaulk",
		role: "Tax Accountant",
		username: "fchaulkg",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "ppollastrinoh@goo.gl",
		id: "fbc1490d-9e4d-419c-ad0a-849e0319ea9d",
		imageUrl: "https://robohash.org/possimusetaut.png?size=50x50&set=set1",
		location: "Paltashaco",
		name: "Paxon Pollastrino",
		role: "VP Sales",
		username: "ppollastrinoh",
		website: "https://opensause.vercel.app",
	},
	{
		about: "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "vrosbothami@virginia.edu",
		id: "9bd4d459-a6cf-4bc2-b1f2-81dd9a28e66d",
		imageUrl: "https://robohash.org/sapienteillumet.png?size=50x50&set=set1",
		location: "Dammarie-les-Lys",
		name: "Vidovik Rosbotham",
		role: "Nurse Practicioner",
		username: "vrosbothami",
		website: "https://opensause.vercel.app",
	},
	{
		about:
			"Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
		contact: {
			github: "https://github.com/pablo-clueless",
			twitter: "https://twitter.com/@pablo_clueless",
			linkedin: "https://linkedin.com/in/samson-okunola",
		},
		email: "kmorettoj@pbs.org",
		id: "a728faba-f8c9-41a8-a4a5-b1455ad40a4f",
		imageUrl: "https://robohash.org/autdolorratione.png?size=50x50&set=set1",
		location: "Gangbei",
		name: "Kial Moretto",
		role: "Health Coach III",
		username: "kmorettoj",
		website: "https://opensause.vercel.app",
	},
] satisfies UserProps[]
